package main.sakura_rain.seven.main;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @ClassName MainContainer
 * @function [业务功能]
 * @notice 持久化操作不做业务上处理
 * @Author lcz
 * @Date 2020/06/06 00:27
 */
public class MainContainer {
    public static JTree tree1;
    public static JTabbedPane tabbedPane1;
    public static JPanel outerPanel;
    public static JToolBar topTool;
    public static JPanel mainPanel;
    public static JSplitPane mainSplitPanel;
    public static JPanel Tab_Two;
    public static JPanel Tab_Three;
    public static JPanel Tab_ONE;


    static {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private static void $$$setupUI$$$() {
        outerPanel = new JPanel();
        outerPanel.setLayout(new GridBagLayout());
        topTool = new JToolBar();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        outerPanel.add(topTool, gbc);
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        outerPanel.add(mainPanel, gbc);

        mainSplitPanel = new JSplitPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(mainSplitPanel, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        mainSplitPanel.setLeftComponent(scrollPane1);
        mainSplitPanel.setDividerLocation(200);

        DefaultMutableTreeNode root = new DefaultMutableTreeNode("七樱归纳");
        DefaultMutableTreeNode      parent;
        parent = new DefaultMutableTreeNode("colors");
        root.add(parent);
        parent.add(new DefaultMutableTreeNode("blue"));
        parent.add(new DefaultMutableTreeNode("violet"));
        parent.add(new DefaultMutableTreeNode("red"));
        parent.add(new DefaultMutableTreeNode("yellow"));


        tree1 = new JTree(new DefaultTreeModel(root));
        scrollPane1.setViewportView(tree1);

        tree1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                TreePath path = tree1.getPathForLocation(e.getX(), e.getY());
                if (path == null) {
                    System.out.println("没有按钮被选中。。。");
                }

                tree1.setSelectionPath(path);
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) path.getLastPathComponent();
                System.out.println(node.getChildCount());
                System.out.println(node.getUserObjectPath());
                System.out.println(node.getUserObject());

                e.getClickCount();
                System.out.printf(e.getClickCount() + "");
                System.out.printf(e.getButton() + "");
            }
        });

        final JScrollPane scrollPane2 = new JScrollPane();
        mainSplitPanel.setRightComponent(scrollPane2);
        tabbedPane1 = new JTabbedPane();
        scrollPane2.setViewportView(tabbedPane1);
        Tab_ONE = new JPanel();
        Tab_ONE.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Tab_ONE", Tab_ONE);
        Tab_Two = new JPanel();
        Tab_Two.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Tab_ONE", Tab_Two);
        Tab_Three = new JPanel();
        Tab_Three.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Tab_ONE", Tab_Three);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return outerPanel;
    }

}
