package main.sakura_rain.seven.main;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @ClassName OrangeSeven
 * @function [业务功能]
 * @notice 持久化操作不做业务上处理
 * @Author lcz
 * @Date 2020/06/05 17:28
 */
public class OrangeSeven {
    private JTree tree1;
    private JTabbedPane tabbedPane1;
    private JPanel outerPanel;
    private JPanel mainPanel;
    private JSplitPane mainSplitPanel;
    private JPanel Tab_Two;
    private JPanel Tab_Three;
    private JPanel Tab_ONE;
    private JScrollPane LeftPanel;

    public static void main(String[] args) {
        OrangeSeven orangeSeven = new OrangeSeven();
        JFrame jFrame = new JFrame();

        jFrame.setContentPane(orangeSeven.outerPanel);


        jFrame.setTitle("七樱");
        /*黄金分割比例*/
        jFrame.setSize(900, 600);
        jFrame.setLocationRelativeTo(null);
        jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jFrame.setVisible(true);
    }

    public JPanel getOuterPanel() {
        return outerPanel;
    }

    public OrangeSeven() {

        tree1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        outerPanel = new JPanel();
        outerPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        outerPanel.add(mainPanel, gbc);
        mainSplitPanel = new JSplitPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(mainSplitPanel, gbc);
        LeftPanel = new JScrollPane();
        mainSplitPanel.setLeftComponent(LeftPanel);
        tree1 = new JTree();
        LeftPanel.setViewportView(tree1);
        final JScrollPane scrollPane1 = new JScrollPane();
        mainSplitPanel.setRightComponent(scrollPane1);
        tabbedPane1 = new JTabbedPane();
        scrollPane1.setViewportView(tabbedPane1);
        Tab_ONE = new JPanel();
        Tab_ONE.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Tab_ONE", Tab_ONE);
        Tab_Two = new JPanel();
        Tab_Two.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Tab_Two", Tab_Two);
        Tab_Three = new JPanel();
        Tab_Three.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Tab_Three", Tab_Three);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return outerPanel;
    }
}
